stages:
  - build
  - test_v15
  - test_v14
  

terraformbuild:
  tags:
    - terraform
  stage: build
  before_script:
    - rm -rf /terraform_builds/
    - mkdir -p /terraform_builds/
  script:  
    - echo "build terraform binary"
    - make fmt
    - go build
    - ls -lrt
  after_script:
    - cp terraform-provider-bigip /terraform_builds/
    
    
terraformv15:
  tags:
    - terraform
  stage: test_v15
  before_script:  
    - cp -r /terraform_builds/terraform-provider-bigip .
    - ls -lrt
  script:
    - echo "Running tests on bigip version 15"
    - BIGIP_USER="$BIGIP_USERNAME_V15" BIGIP_PASSWORD="$BIGIP_PASSWORD_V15" BIGIP_HOST="$BIGIP_HOST_V15" TF_ACC=1 make testacc
  allow_failure: true

terraformv14:
  tags:
    - terraform
  stage: test_v14
  before_script:
    - cp -r /terraform_builds/terraform-provider-bigip .
    - ls -lrt
  script:  
    - echo "Running tests on bigip version 14"
    - BIGIP_USER="$BIGIP_USERNAME_V14" BIGIP_PASSWORD="$BIGIP_PASSWORD_V14" BIGIP_HOST="$BIGIP_HOST_V14" TF_ACC=1 make testacc
  

