#Original work from https://github.com/DealerDotCom/terraform-provider-bigip
#Modifications Copyright 2019 F5 Networks Inc.
#This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#If a copy of the MPL was not distributed with this file,You can obtain one at https://mozilla.org/MPL/2.0/.

dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.16.x"

git:
  depth: 1

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

script:
- make test
- make website-lint

branches:
  only:
  - master
  - devel
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on
